#!e:\01_SOFT\Python27\python.exe
# EASY-INSTALL-SCRIPT: 'sae-python-dev==1.3.6','saecloud'
__requires__ = 'sae-python-dev==1.3.6'
__import__('pkg_resources').run_script('sae-python-dev==1.3.6', 'saecloud')
